spring.application.name=nexus-core-api
# API PREFIX (Optional but good for versioning)
server.servlet.context-path=/api
ai.service.url=${AI_SERVICE_URL:http://localhost:8000}
jwt.secret=mysupersecretmysupersecretmysupersecretmysupersecret

spring.datasource.url=jdbc:postgresql://ep-young-art-ab2obkrv-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require

# The Credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VF5IfC6htGZK

#Flyway Enabled For Database Control
spring.flyway.enabled=true
# Hibernate Settings (Auto-create tables)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect